title: Our beat
hero_image: images/banner.png
description: Use your micro:bit to make a theme tune for your Code Club
version: 1
listed: false
copyedit: false
last_tested: "2025-07-11"
steps:
  - title: What you will make
  - title: Simple melody
    completion:
      - engaged
  - title: micro:bit band
    completion:
      - internal
  - title: Challenge
    challenge: true
    completion:
      - external
